package com.example.gomotion;


public abstract class Excercise
{
	//Online Excercises
	protected Integer ID;
	protected Integer userID;
	protected boolean shouldShare;
	
	//All excercises
	protected int timeStamp;
	
	//If id isn't null then the record has been stored on the server
	public boolean isStored()
	{
		return ID != null;
	}
	
	//Save a record, ID is generated by MySql, returns whether successful
	protected abstract boolean saveToDatabase();
	
	//Online or offline user functions
	public void setOnline(int userID)
	{
		this.userID = userID;
	}
	public boolean isOnline()
	{
		return userID != null;
	}
	
	//Try to save to the database, cache in case of failure
	public boolean save(int userID)
	{
		//Set UserID (Facebook ID)
		this.userID = userID;
		
		//Save to database, cache on failure
		if(!saveToDatabase())
		{
			Cache.append(this);
			return false;
		}
		
		//Success
		return true;
	}
	
	//Getters And Setters
	public Integer getID()
	{
		return ID;
	}
	public void setID(Integer iD)
	{
		ID = iD;
	}
	public Integer getUserID()
	{
		return userID;
	}
	public void setUserID(Integer userID)
	{
		this.userID = userID;
	}
	public int getTimeStamp()
	{
		return timeStamp;
	}
	public void setTimeStamp(int timeStamp)
	{
		this.timeStamp = timeStamp;
	}

}
