package com.example.gomotion;


public abstract class Excercise
{
	//Online Excercises
	protected Integer ID;
	protected Integer userID;
	protected boolean shouldShare;
	
	//All excercises
	protected int timestamp;
	
	
	//If id isn't null then the record has been stored on the server
	public boolean isStored()
	{
		return ID != null;
	}
	
	//Get a record from the server to view with the app
	public abstract void getFromDatabase(int id);
	
	//Save a record, ID is generated by MySql, returns whether successful
	protected abstract boolean saveToDatabase();
	
	//Try to save to the database, cache in case of failure
	public boolean tryUpload(int userID)
	{
		//Set UserID (Facebook ID)
		this.userID = userID;
		
		//Save to database, cache on failure
		if(!saveToDatabase())
		{
			Cache.append(this);
			return false;
		}
		
		//Success
		return true;
	}
	
	public abstract void writeToFile(java.io.OutputStream writer);
}
