package com.example.gomotion;


public abstract class Exercise
{
	//Variables for every Record child class
    private Integer id;
    
    private int timestamp;
    private boolean shouldShare;
    
    //If id isn't null then the record has been stored on the server
    public boolean isStored()
    {
    	return id != null;
    }
    
//    //Get a record from the server to view with the app
//    public abstract void get(int id);
//    
//    //Save a record, ID is generated by MySql
//    public abstract void save();
    
    //Getters
    public boolean getShouldShare()
    {
        return shouldShare;
    }
    
}
